White box test to reach 100% coverage
matthew-mca/CSC3056-2024-G44 pull request #9
Opened 2024-04-05 01:51 UTC by KentonMcCombQUB

Data Utilities White box testing coverage at 100%

2024-04-05 13:56 UTC, matthew-mca commented on Lab3/JFreeChart/source/org/jfree/data/DataUtilitiesTest.java
> +    }
Invalid inputs should return 0. We do not expect an `IndexOutOfBoundsException` here.

2024-04-05 13:56 UTC, matthew-mca commented on Lab3/JFreeChart/source/org/jfree/data/DataUtilitiesTest.java
> +    }
Adding an int and null together does not work in Java as far as I know. The spec for this function says that `null` is not permitted, but I have no clue if this means the overall data object or if it means all the numbers in it must also not be null. What happens when you run the test? I feel like the test should either raise an exception or return 0, I don't think it should just treat `null` as 0.

2024-04-05 13:56 UTC, matthew-mca commented on Lab3/JFreeChart/source/org/jfree/data/DataUtilitiesTest.java
> +    }
Same as above comment, not sure what I expect to happen here according to the spec (cause it's quite vague) but I don't think nulls should just be ignored entirely.

2024-04-05 13:56 UTC, matthew-mca commented on Lab3/JFreeChart/source/org/jfree/data/DataUtilitiesTest.java
> +    }
Invalid input should return 0 should it not?

2024-04-05 13:56 UTC, matthew-mca commented on Lab3/JFreeChart/source/org/jfree/data/DataUtilitiesTest.java
> +        data.addValue("3", 30);
What are the strings here for? Haven't seen these before.

2024-04-05 20:06 UTC, KentonMcCombQUB commented on Lab3/JFreeChart/source/org/jfree/data/DataUtilitiesTest.java
> +    }
The test passes fully, as my understanding was that it will be equal to 2 + 0. Therefore 2 as expected outcome of total for column with 2 and null will still equal 2
<img width="544" alt="Screenshot 2024-04-05 at 21 05 40" src="https://github.com/matthew-mca/CSC3056-2024-G44/assets/97742563/92a64d53-94bb-42c6-ad19-25a81fab862f">

2024-04-05 20:10 UTC, KentonMcCombQUB commented on Lab3/JFreeChart/source/org/jfree/data/DataUtilitiesTest.java
> +    }
Return is 0

![image](https://github.com/matthew-mca/CSC3056-2024-G44/assets/97742563/64a87d0f-8e68-4459-953c-ec4df41c3897)

2024-04-05 20:32 UTC, KentonMcCombQUB commented on Lab3/JFreeChart/source/org/jfree/data/DataUtilitiesTest.java
> +    }
updated as try catch is not needed, my understanding was that null is interupted as a 0 and therefore essentially ignored?
<img width="449" alt="Screenshot 2024-04-05 at 21 31 44" src="https://github.com/matthew-mca/CSC3056-2024-G44/assets/97742563/99c52961-e771-4a2a-8378-7b8db9980c2b">

2024-04-05 21:36 UTC, KentonMcCombQUB commented on Lab3/JFreeChart/source/org/jfree/data/DataUtilitiesTest.java
> +        data.addValue("3", 30);
for this particular was unsure why the quotes seemed to prevent following error 
<img width="575" alt="Screenshot 2024-04-05 at 22 35 27" src="https://github.com/matthew-mca/CSC3056-2024-G44/assets/97742563/808bcb10-dac8-498c-bc06-6121caa84e15">

2024-04-06 12:16 UTC, matthew-mca commented on Lab3/JFreeChart/source/org/jfree/data/DataUtilitiesTest.java
> +    }
Yes, but that assertEquals is unreachable since there is a fail statement directly after calling `calculateRowTotal`.
We do not expect an IndexOutOfBoundsException, so if one is not raised it should be removed. If one is raised,
there should be a fail statement inside the `catch` block, not the `try` block.

2024-04-06 12:19 UTC, matthew-mca commented on Lab3/JFreeChart/source/org/jfree/data/DataUtilitiesTest.java
> +        data.addValue("3", 30);
`addValue` requires 3 values: a value to insert, a row key, and a column key.

2024-04-06 12:31 UTC, matthew-mca requested changes
Some of the testing is still not expecting the correct output, or you have manually set the test to the correct output itself.

2024-04-06 12:31 UTC, matthew-mca commented on Lab3/JFreeChart/source/org/jfree/data/DataUtilitiesTest.java
> +            result = 0.0; // Return 0.0 if an IndexOutOfBoundsException
This is incorrect - you are manually setting the value to 0 itself. The `calculateColumnTotal` value should return 0 on its own with invalid input. Doing *anything* else should fail the test. I'm guessing the method throws an `IndexOutOfBoundsException` - there should be a fail statement in the `catch` block since the spec does not expect this error to be raised.

2024-04-06 13:46 UTC, KentonMcCombQUB commented on Lab3/JFreeChart/source/org/jfree/data/DataUtilitiesTest.java
> +    }
Have moved the fail statement to be within the `catch` block, instead of `try` block

2024-04-06 15:35 UTC, matthew-mca reviewed
Just one commented line of code that needs removed. I would approve this even with that commented line in, but I have just one more request here - can you comment a screenshot of the coverage in Eclipse showing 100% line coverage and branch coverage for the `DataUtilities` class please?

2024-04-06 15:35 UTC, matthew-mca commented on Lab3/JFreeChart/source/org/jfree/data/DataUtilitiesTest.java
> +        // values2D.addValue(3, 0, 1); // Second column
Is this line needed? If not, can you delete it please

2024-04-06 16:00 UTC, KentonMcCombQUB commented
This change adds test cases to expand the code coverage of the DataUtilities class. The line coverage has been increased to 97.7%*, while the branch coverage has been increased to 100.0%.
Branch Coverage
![image](https://github.com/matthew-mca/CSC3056-2024-G44/assets/97742563/29b0788d-6ccd-41d4-8f60-66e2de0f0022)

Line Coverage
![image](https://github.com/matthew-mca/CSC3056-2024-G44/assets/97742563/1649c173-23ac-411f-8ce4-db17d1a1ce29)


*97.7% coverage only as `public abstract class DataUtilities {` not covered, all other lines covered, as seen in screenshots below.
<img width="771" alt="Screenshot 2024-04-06 at 16 57 21" src="https://github.com/matthew-mca/CSC3056-2024-G44/assets/97742563/ccbc0f08-289e-45dc-956a-17c9797a16d8">
<img width="737" alt="Screenshot 2024-04-06 at 16 57 34" src="https://github.com/matthew-mca/CSC3056-2024-G44/assets/97742563/b8a83bd6-77ad-4ae1-828b-cde54b61d1ab">

2024-04-06 16:34 UTC, matthew-mca approved these changes

2024-04-06 16:34 UTC, merged